// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjwvicrkfklzddpbubjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqd3ZpY3JrZmtsemRkcGJ1YmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDUwMDQsImV4cCI6MjA2NzMyMTAwNH0.HmhW5l3qF0vh-dlB435zp9WncLSRvz9bLGb524pksxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});